# -*- coding: utf-8 -*-
"""CalculadoraEBAC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9hmXkwn4LhX3DDuWfo_MbptVjjlLKoU
"""

print("\nVocê está na calculadora, insira os números e escolha a operação desejada.\n")

#inicio do loop para obter o primeiro número
while True:
    resposta1 = input("\nPrimeiro número: ") #coleta a resposta do usuário
    try: #tentativa de conversão para float
        num1 = float(resposta1) #converte a resposta em um número decimal (variável de ponto flutuante)
        break  # Sai do loop se a conversão for bem-sucedida
    except ValueError:
        # Se ocorrer um erro de conversão, informa o usuário e pede para tentar novamente
        print("\nEntrada inválida. Por favor, digite um número.")

#inicio do loop para obter o segundo número
while True:
    resposta2 = input("\nSegundo número: ") #coleta a resposta
    try: #tenta converter para float
        num2 = float(resposta2)
        break
    except ValueError: #se ocorrer um erro de conversão volta o loop
        print("\nEntrada inválida. Por favor, digite um número.")

#informa quais foram os números escolhidos
print("\nSeu primeiro número é:", num1)
print("\nSeu segundo número é:", num2)

#inicio do loop para escolher a operação
while True:

  #apresenta as opções disponíveis para o usuário
  print("\nDigite o número da opção desejada: ")
  print("\n1 - Adição" " (",(num1), "+", (num2),")") #informa também qual operação será realizada utilizando os números escolhidos
  print("\n2 - Subtração" " (",(num1), "-", (num2),")") #informa também qual operação será realizada utilizando os números escolhidos
  print("\n3 - Multiplicação" " (",(num1), "vezes", (num2),")") #informa também qual operação será realizada utilizando os números escolhidos
  print("\n4 - Divisão" " (",(num1), "dividido por", (num2),")")  #informa também qual operação será realizada utilizando os números escolhidos
  print("\n5 - Resto de divisão (resto da divisão de",(num1),"por",(num2),")") #informa também qual operação será realizada utilizando os números escolhidos
  print("\n6 - Potenciação" " (",(num1), "elevado a", (num2),")")  #informa também qual operação será realizada utilizando os números escolhidos
  print("\n7 - Sair") #informa a opção de sair do programa

  resposta_opcao = input("\nOpção: ") #coleta a resposta do usuário

  try:
    opcao = int(resposta_opcao) #converte a resposta em um número inteiro

    if opcao == 1: #caso a resposta seja 1
        print("\nVocê escolheu Adicionar!")
        print("A operação realizada foi",(num1),"mais",(num2),"resultando em:",(num1 + num2)) #realiza a operação
        continue #continua com o programa

    elif opcao == 2: #caso a resposta seja 2
        print("\nVocê escolheu Subtrair!")
        print("A operação realizada foi",(num1),"menos",(num2),"resultando em:",(num1 - num2)) #realiza a operação
        continue #continua com o programa

    elif opcao == 3: #caso a resposta seja 3
        print("\nVocê escolheu Multiplicar!")
        print("A operação realizada foi",(num1),"vezes",(num2),"resultando em:",(num1 * num2)) #realiza a operação
        continue #continua com o programa

    elif opcao == 4: #caso a resposta seja 4
          print("\nVocê escolheu Dividir!")
          print("A operação realizada foi",(num1),"dividido por",(num2),"resultando em:",(num1 / num2)) #realiza a operação
          continue #continua com o programa

    elif opcao == 5: #caso a resposta seja 5
          print("\nVocê escolheu Resto da divisão!")
          print("Resta",(num1 % num2),"quando",(num1),"é dividido por",(num2)) #realiza a operação
          continue #continua com o programa

    elif opcao == 6: #caso a resposta seja 6
          print("\nVocê escolheu Potenciação!")
          print("A operação realizada foi",(num1),"elevado a",(num2),"resultando em:",(num1 ** num2)) #realiza a operação
          continue #continua com o programa

    elif opcao == 7: #caso a resposta seja 7
          print("\nVocê escolheu sair.")
          break #encerra do programa

    else: #caso a resposta seja um número diferente das opções
        print("\nOpção inválida! Tente novamente.") #informa ao usuário que a opção é inválida
        continue #continua com o programa

  except ValueError: #caso a resposta não seja um número inteiro
        print("\nOpção inválida! Escolha um número.") #informa ao usuário que a opção é inválida
        continue #continua com o programa